version: "3.8"

services:
  bff:
    build:
      target: bff-image
    ports:
      - "127.0.0.1:5063:5063"
    environment:
      - HOST=0.0.0.0
      - PORT=5063

  prometheus:
    image: prom/prometheus:v2.55.0
    ports:
      - "127.0.0.1:9091:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./metrics/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
